// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: book.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author, isbn)
VALUES ($1, $2, $3)
RETURNING id, title, author, isbn, is_available, created_at, updated_at
`

type CreateBookParams struct {
	Title  string
	Author string
	Isbn   pgtype.Text
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook, arg.Title, arg.Author, arg.Isbn)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Isbn,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, isbn, is_available, created_at, updated_at FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id pgtype.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Isbn,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, isbn, is_available, created_at, updated_at FROM books
WHERE is_available = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Isbn,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookAvailability = `-- name: UpdateBookAvailability :one
UPDATE books 
SET 
  is_available = $2, 
  updated_at = NOW()
WHERE id = $1
RETURNING id, title, author, isbn, is_available, created_at, updated_at
`

type UpdateBookAvailabilityParams struct {
	ID          pgtype.UUID
	IsAvailable bool
}

func (q *Queries) UpdateBookAvailability(ctx context.Context, arg UpdateBookAvailabilityParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBookAvailability, arg.ID, arg.IsAvailable)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Isbn,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
