// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID          pgtype.UUID
	Title       string
	Author      string
	Isbn        pgtype.Text
	IsAvailable bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
