// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID          uuid.UUID
	Title       string
	Author      string
	Isbn        sql.NullString
	IsAvailable bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
